### ISSUE TITLE
Chance that it will error when enabling shadow.

### ISSUE THREAD

**Issue by GhostieSpook** [ajmeese7/readme-ascii#3]
I was inputting a custom color and when I generated without shadow it worked fine, but then when I enabled shadow it errored and then didn't generate whatsoever.

**Comment by ajmeese7** [comment]
There is sometimes a timeout error with Heroku when the application is first started up. Did you click the `Generate Image` button again to see if it worked the second or third time?

**Comment by GhostieSpook** [comment]
Tried it about 10 times at that point it stopped generating even the error message. I eventually got it to work, but I just wanted to make it known.

**Comment by ajmeese7** [comment]
Thanks for letting me know. I don't know why that is happening, but I'll look at the logs and see if I can find anything. I will let you know if I find a fix.

**Comment by ajmeese7** [comment]
I think the issue may have something to do with startup times after the application goes to sleep. I registered the application on [Kaffeine](https://kaffeine.herokuapp.com/), so hopefully the issue will go away now.

Try it again and let me know if you're still having any problems.
